### PR TITLE
Create use-case-3.md

### PR DESCRIPTION
**Pull request by MadaraUchiha**
#goodnessSquad

### CODE REVIEW

**Comment by benjamingr** [comment]
That is - is there any reason why a tool that does this can't be written in userland as well as it can be in userland code?

**Comment by MadaraUchiha** [comment]
@benjamingr A similar thing was implemented in userland, at the very least it can (not saying it necessarily should) be implemented by node, purely in JS code, regardless of V8 capabilities.

**Comment by Bnaya** [comment]
The concurrency of map is the most useful feature of bluebird,
And it will be great to have something like that as part of the language.
c# has 
https://msdn.microsoft.com/en-us/library/system.threading.tasks.paralleloptions.maxdegreeofparallelism(v=vs.110).aspx
Which is conceptually similar

**Comment by benjamingr** [comment]
> c# has

That's for actually running things threaded - C# doesn't offer a parallelism option for `Task.WhenAny` (Promise.race) or `Task.WhenAll` (Promise.all)

In either case - any proposal to extend a promise built in would go through TC39 (I'll be happy to try help anyone interested in pursuing that) but this is not what this repo is for.

I am specifically looking at:

 - Capabilities or APIs
 - That node can expose without changing JavaScript
 - That would enable people to build things in userland or improve their debugging experience to match the capabilities of userland libraries like bluebird.

**Pull request closed without merging**
