### PR TITLE
Add async_hook option

### PR DESCRIPTION
**Pull request by benjamingr**

### CODE REVIEW

**Comment by benjamingr** [comment]
@getify can you please take a look and OK this (or ask for changes)?

**Comment by benjamingr** [comment]
> Is "intercept synchronous throws" intended to mean all forms of JS exception, or only explicit throw statments?

Explicitly only `throw` statements.

> Also, what is an APM?

Application performance monitoring - that is tools that report errors to you. That is a developer would have a choice to get notified in their error or performance tracker when `throw` happens in a promise constructor/then after the promise has resolved.

**Comment by getify** [comment]
> Explicitly only throw statements.

The use-case I wrote here is focused on accidental exceptions, not explicit throws or rejections. Seems like perhaps async_hook is more appropriate for a different (perhaps new?) use-case rather than this one.

**Comment by benjamingr** [comment]
> The use-case I wrote here is focused on accidental exceptions

I think an async_hook would be an interesting way to solve that - even if Node.js can't or won't change the default behavior - I'd still want to know about these.

**Comment by benjamingr** [comment]
I'm going to go ahead and land this as a possible solution.

We have discussed it and decided to pursue both options: approach the TC and ask for a possible spec change as well as try and enable it in Node.js as part of the async_hooks redesign.

**Pull request merged**
